services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: notification-service-mqtt
    restart: unless-stopped
    network_mode: host

  my-app:
    build: .
    container_name: notification-service
    restart: unless-stopped
    network_mode: host
